version: '2'
services:
  app:
    image: devteds/rails-api-example
    ports:
      - "80:3000"
    environment:
      DB_USER: group6user
      DB_NAME: group6db
      DB_PASSWORD: group6password
      DB_HOST: pd1w5oyng230iaa.cg69tc0gb51t.us-east-1.rds.amazonaws.com
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
      SECRET_KEY_BASE: 5156ca5a10c6842c4359d9a78ba14a4ba91cee9394d2e87bb783a0f770469d6afd725d40346d328b705cb2b74ef7de2005701c3449a1dbd1d1bc163ce3b67ec1
